<a href="https://colab.research.google.com/github/NBushey26/ds2002-fa26/blob/main/2026_10_16_%E2%80%94_Walmart_Warm_Up_SKU_Mess_%E2%80%94_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Walmart Warm-Up SKU Mess

**Lab — 2026-10-16 · Fall 2026**  

---

## Lab 08 — Walmart Warm-Up (SKU Mess)

This lab uses the **real midterm data** in `../06-midterm-walmart/data/`. It's a warm-up so you hit the ground running on the project. On Kaggle/Colab, upload the data folder or adjust the path.

*If the file isn't found, the cell falls back to a small inline sample so the notebook still runs.*

In [1]:
import pandas as pd
PATH = '/content/product_catalog.csv'
try:
    cat = pd.read_csv(PATH)
except FileNotFoundError:
    from io import StringIO
    cat = pd.read_csv(StringIO('sku,product_name,category\nPT-12,pop-tarts strawberry,Breakfast Foods\nSKU#459812,Strawberry Pop-Tart,Breakfast\nPOPTART-STRAW,Pop-Tarts Strawberry,Breakfast'))
cat.head()

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack

### Q1 — How many rows look like Pop-Tart products?

Filter on `product_name` containing `pop`, case-insensitively. Print the count and the matching rows.

In [2]:
# TODO (hint: .str.lower().str.contains('pop'))
pop_rows = cat[cat['product_name'].str.lower().str.contains('pop', na=False)]
print(f"Count: {len(pop_rows)}")
pop_rows

Count: 4

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack

### Q2 — Which SKUs and names all mean *strawberry* Pop-Tart?

List them. Then note which Pop-Tart rows are **not** strawberry — those must stay separate, and saying so is part of the answer.

In [3]:
# TODO
pop_rows = cat[cat['product_name'].str.lower().str.contains('pop', na=False)]
pop_rows[['sku', 'product_name']]

             sku          product_name
0          PT-12  pop-tarts strawberry
1     SKU#459812   Strawberry Pop-Tart
2  POPTART-STRAW  Pop-Tarts Strawberry
3  PT_STRAWBERRY  pop-tarts strawberry

**Pop-Tart rows that are a different product:** _There are none that are not strawberry_

### Q3 — Build the mapping

A dict from each variant SKU to one canonical SKU. Then apply it in a way that leaves unmapped SKUs as themselves rather than turning them into `NaN` — that single mistake silently deletes most of the catalog.

In [4]:
# TODO
sku_mapping = {
    'SKU#459812': 'PT-12',
    'POPTART-STRAW': 'PT-12',
    'PT_STRAWBERRY': 'PT-12',
    'LTBEER24': 'BEER-24',
    'BAT-AA4': 'BATT_AA_4PK',
    'MONOPOLY-01': 'BG-MONO',
    'GAME-MONO': 'BG-MONO',
    'WHITEBREAD': 'BREAD-WH',
    'PNUTBTR-16': 'PB-16',
    'CANDLE-EMRG': 'CNDL-EM',
    'CNSOUP-01': 'SOUP-CAN',
    'PLAYCARD-STD': 'CARDS-01',
    'CHIPVARIETY': 'CHIPS-VP',
    'HDTARP-01': 'TARP-HD',
    'LED-FLASH': 'FLASH-01',
    'PAPERTOWEL6': 'PTOWEL-6'
}

cat['canonical_sku'] = cat['sku'].map(sku_mapping).fillna(cat['sku'])
cat[['sku', 'canonical_sku', 'product_name']].head(10)

             sku canonical_sku           product_name
0          PT-12         PT-12   pop-tarts strawberry
1     SKU#459812         PT-12    Strawberry Pop-Tart
2  POPTART-STRAW         PT-12   Pop-Tarts Strawberry
3  PT_STRAWBERRY         PT-12   pop-tarts strawberry
4         WTR-24        WTR-24     BOTTLED WATER 24PK
5      WATER24PK     WATER24PK  Bottled Water 24-Pack
6       WTR_24PK      WTR_24PK        Water - 24 Pack
7       BATT-100      BATT-100       BATTERIES AA 4PK
8        BAT-AA4   BATT_AA_4PK    AA Batteries 4-Pack
9    BATT_AA_4PK   BATT_AA_4PK    AA Batteries 4-Pack

### Q4 — Normalize `category`

Strip and title-case, then show the distinct values before and after with counts. Note any pair that is still two labels for one thing — `Breakfast` and `Breakfast Foods` are not the same string but they are the same category.

In [5]:
# TODO
print("Before")
print(cat['category'].value_counts())

cat['clean_category'] = cat['category'].str.strip().str.title()
cat['clean_category'] = cat['clean_category'].replace({'Breakfast Foods': 'Breakfast', 'Groceries': 'Grocery'})

print("\nAfter")
print(cat['clean_category'].value_counts())

Before
category
Emergency              5
Emergency Supplies     3
EMERGENCY              3
ENTERTAINMENT          3
GROCERY                3
Breakfast              2
entertainment          2
household              2
ELECTRONICS            2
health                 2
Baby                   2
Electronics            1
ALCOHOL                1
Alcoholic Beverages    1
breakfast              1
Breakfast Foods        1
Groceries              1
Grocery                1
electronics            1
snacks                 1
grocery                1
HOUSEHOLD              1
Snacks                 1
Household              1
baby                   1
Baby Products          1
emergency              1
Name: count, dtype: int64

After
clean_category
Emergency              9
Grocery                6
Entertainment          5
Breakfast              4
Electronics            4
Household              4
Baby                   3
Emergency Supplies     3
Health                 2
Snacks                 2
Alcoholic Beverages    1
Alcohol                1
Baby Products          1
Name: count, dtype: int64

### Q5 — Find the fragmentation you have not spotted yet

Hand-scanning a catalog does not scale. **TODO:** build a candidate list programmatically — normalize each product name (lowercase, strip punctuation, sort the words) and group by that, then show any group holding more than one SKU.

This is the workflow from Monday's lecture, and it is how you will actually approach the full catalog on the midterm.

In [6]:
# TODO
import string

def normalize_name(name):
    if not isinstance(name, str):
        return ''
    translator = str.maketrans('', '', string.punctuation)
    clean = name.lower().translate(translator)
    return ' '.join(sorted(clean.split()))

cat['normalized_name'] = cat['product_name'].apply(normalize_name)
fragmented = cat.groupby('normalized_name').filter(lambda x: len(x['sku'].unique()) > 1)

print(f"Found {len(fragmented)} rows across fragmented groups:")
for name, group in fragmented.groupby('normalized_name'):
    print(f"\nGroup: '{name}'")
    display(group[['sku', 'product_name', 'clean_category']])

Found 28 rows across fragmented groups:

Group: '24pack beer light'

         sku          product_name       clean_category
12   BEER-24  Light Beer (24-pack)  Alcoholic Beverages
13  LTBEER24  Light Beer (24-pack)              Alcohol

Group: '4pack aa batteries'

           sku         product_name      clean_category
8      BAT-AA4  AA Batteries 4-Pack  Emergency Supplies
9  BATT_AA_4PK  AA Batteries 4-Pack           Emergency

Group: 'board game monopoly'

            sku           product_name clean_category
14      BG-MONO    Monopoly Board Game  Entertainment
15  MONOPOLY-01    Monopoly Board Game  Entertainment
16    GAME-MONO  Board Game - Monopoly  Entertainment

Group: 'bread white'

           sku product_name clean_category
23    BREAD-WH  WHITE BREAD        Grocery
24  WHITEBREAD  WHITE BREAD        Grocery

Group: 'butter peanut'

           sku   product_name clean_category
25       PB-16  PEANUT BUTTER        Grocery
26  PNUTBTR-16  Peanut Butter        Grocery

Group: 'candles emergency'

            sku         product_name clean_category
27      CNDL-EM  Candles (Emergency)      Emergency
28  CANDLE-EMRG    Emergency Candles      Emergency

Group: 'canned soup'

          sku   product_name clean_category
21   SOUP-CAN  Soup - Canned        Grocery
22  CNSOUP-01    Canned Soup        Grocery

Group: 'cards playing'

             sku   product_name clean_category
17      CARDS-01  Playing Cards  Entertainment
18  PLAYCARD-STD  PLAYING CARDS  Entertainment

Group: 'chips pack variety'

            sku          product_name clean_category
33     CHIPS-VP  Variety Pack - Chips         Snacks
34  CHIPVARIETY    Chips Variety Pack         Snacks

Group: 'duty heavy tarp'

          sku       product_name clean_category
43    TARP-HD    Heavy Duty Tarp      Emergency
44  HDTARP-01  TARP - HEAVY DUTY      Emergency

Group: 'flashlight led'

          sku    product_name clean_category
10   FLASH-01  FLASHLIGHT LED      Emergency
11  LED-FLASH  FLASHLIGHT LED      Emergency

Group: 'paper towels'

            sku  product_name clean_category
35     PTOWEL-6  Paper Towels      Household
36  PAPERTOWEL6  Paper Towels      Household

Group: 'poptarts strawberry'

             sku          product_name clean_category
0          PT-12  pop-tarts strawberry      Breakfast
2  POPTART-STRAW  Pop-Tarts Strawberry      Breakfast
3  PT_STRAWBERRY  pop-tarts strawberry      Breakfast

### Q6 — Prove the mapping is safe

**TODO:** assert that applying your mapping produced no nulls in the canonical column and did not change the number of rows. Consolidation renames; it never adds or removes.

In [7]:
# TODO
assert cat['canonical_sku'].isna().sum() == 0, "Mapping created null values"
assert len(cat) == len(cat['canonical_sku']), "Row count changed during consolidation"
print("It works! Mapping is safe. There are zero nulls produced and total row count is preserved")

It works! Mapping is safe. There are zero nulls produced and total row count is preserved

### Write-up

**a)** Name two product families beyond Pop-Tarts that appear fragmented, and how you would group them.

**b)** Where does consolidation stop being a data-cleaning task and become a business decision? Give one example from this catalog where you genuinely are not sure, and say who you would ask.

a. Toilet paper and paper towels appeared fragmaneted and I would group them either by their specific products and just standardize the spelling and the sku or I could combine them into a uniform "household" category standardized from how they are already grouped.

b.It stops being data cleaning when you get into the more nitty gritty details of the products such as how they are packaged or what brand is being sold. An example from this catalog would be in the different brands of canned soup sold and I would ask the store managers to get more specifics on products that are flying off the shelves.